### ISSUE TITLE
Use the standard STEPS Docker image

### ISSUE THREAD

**Issue by tristan0x** [kotsaloscv/multiscale_run_dimage#3]
Hey @kotsaloscv 
I noticed this in `recipe/Dockerfile`:
https://github.com/kotsaloscv/multiscale_run_dimage/blob/54ec7bd982fc777a38eebf7356b400a41f79fd0e/recipe/Dockerfile#L105C5-L105C134

I have 2 questions about it:
1. Do you confirm this is the only change compared to the supported STEPS Docker image?
1. There is a CMake option `TARGET_NATIVE_ARCH` that is supposed to address exactly what you need. Have you tried it i.e `cmake -DTARGET_NATIVE_ARCH:BOOL=FALSE` before adding the compiler flag? I have realized this option is set to TRUE in the `cnsoist/steps` on DockerHub even though it shouldn't. I need both my M1 laptop to rebuild the images and bandwidth to upload them to Docker Hub, so not before next Monday. In the meantime, if you have time, you can validate that `TARGET_NATIVE_ARCH:BOOL=FALSE` fix the issue.

**Comment by kotsaloscv** [comment]
Hi @tristan0x,
1. I confirm that this is the only change.
2. I could try this CMake option but I am not sure in which system to test it (I could possibly ask Dries to access one such VM and test it).
I will update here once I test it.

**Comment by tristan0x** [comment]
Don't worry about testing it if we don't have access to the cloud environment anymore. I am 100% sure that `-march=native` is only set when `TARGET_NATIVE_ARCH` is set. I will add the capability to set or not this option in the supported Docker image and let you know once this is done.

**Comment by kotsaloscv** [comment]
Hi @tristan0x 

We have checked the `cmake -DTARGET_NATIVE_ARCH:BOOL=FALSE` in a node without avx512 (thanks to Omar) and everything worked fine!
I just pushed the change -> https://github.com/kotsaloscv/multiscale_run_dimage/commit/dc70718ccd8a3df072c7e6e2ec926905d377b31a

Thank you for the remark!

Next step would be to start the recipe on top of STEPS one.

**Comment by tristan0x** [comment]
Thank you very much Omar and @kotsaloscv 
You can use the new Docker image [`cnsoist/steps:5.0.0_beta`](https://hub.docker.com/layers/cnsoist/steps/5.0.0_beta/images/sha256-749e31dd5ec111112809e2b6bcd06a2870d2019ec82721f4698467d112532294?context=repo) on Docker Hub, and the  [PR is ready for review](https://github.com/CNS-OIST/STEPS_Docker/pull/23)!

**Comment by tristan0x** [comment]
> Next step would be to start the recipe on top of STEPS one.

This is the purpose of #1 I can take care of rebasing it if this is fine with you.

**Comment by kotsaloscv** [comment]
That would be great @tristan0x. 
Thank you for taking care of it!

**Comment by tristan0x** [comment]
Taken care of in #1
