### ISSUE TITLE
Where multiscale_run_rat_sscx_S1HL_V7.tar.gz is coming from?

### ISSUE THREAD

**Issue by tristan0x** [kotsaloscv/multiscale_run_dimage#6]
https://github.com/kotsaloscv/multiscale_run_dimage/blob/b42f2cd24b946ed5503c2a745123b77b04a0edae/fetch_multiscale_run.sh#L7C7-L7C40

Is this file stored in the Google Drive storage of the Blue Brain organization ? Otherwise it should.
Are there instructions somewhere to reconstruct this file if needed?

**Comment by kotsaloscv** [comment]
This file is stored in HPC's google drive (so it is in a persistent location).
Essentially it is a stripped down version of multiscale run project. Additionally, the folder includes the circuit on which we perform the simulation.

**Comment by tristan0x** [comment]
thank you
